# Generated by Django 4.0.4 on 2022-05-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_path',
            field=models.CharField(default=False, max_length=32),
        ),
    ]
