# Generated by Django 4.0.4 on 2022-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
