# Generated by Django 4.0.4 on 2022-05-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_user_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_path',
            field=models.CharField(max_length=32),
        ),
    ]
