# Generated by Django 4.0.4 on 2022-06-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_email_verified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileCourseRole',
        ),
    ]
