# Generated by Django 4.0.4 on 2022-05-21 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(default='profile-default.jpg', upload_to=''),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=175)),
                ('price', models.IntegerField(blank=True)),
                ('avatar_url', models.ImageField(default='course-default.svg', upload_to='')),
                ('duration_in_minutes', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('members_amount', models.IntegerField(default=0)),
                ('max_progress_points', models.IntegerField(default=0)),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('course_path', models.CharField(max_length=32)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coursestatus')),
            ],
        ),
    ]
