# Generated by Django 4.0.4 on 2022-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coursestatus_alter_profile_avatar_url_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_path',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
