# Generated by Django 4.0.4 on 2022-05-21 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coursestatus'),
        ),
    ]
