# Generated by Django 4.0.4 on 2022-05-21 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image', models.ImageField(blank=True, upload_to='')),
                ('goal_description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_stars_count', models.IntegerField(default=0)),
                ('two_stars_count', models.IntegerField(default=0)),
                ('three_stars_count', models.IntegerField(default=0)),
                ('four_stars_count', models.IntegerField(default=0)),
                ('five_stars_count', models.IntegerField(default=0)),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseinfo')),
            ],
        ),
        migrations.CreateModel(
            name='CourseFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=256)),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseinfo')),
            ],
        ),
    ]
