# Generated by Django 4.0.4 on 2022-05-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_courseinfo_coursestars_coursefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('course_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.courseinfo')),
            ],
        ),
    ]
