# Generated by Django 4.0.4 on 2022-05-21 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_title_image_courseinfo_title_image_url_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('image_url', models.ImageField(blank=True, upload_to='')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.theme')),
            ],
        ),
    ]
