# Generated by Django 4.0.4 on 2022-05-21 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profilestepstatus_profilestep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.step'),
        ),
    ]
