# Generated by Django 4.0.4 on 2022-05-21 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_profilestep_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_path',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_path',
        ),
        migrations.AddField(
            model_name='course',
            name='path',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='path',
            field=models.CharField(default=datetime.datetime(2022, 5, 21, 16, 27, 4, 281833, tzinfo=utc), max_length=64),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=175)),
                ('image_url', models.ImageField(default='collection-default.svg', upload_to='')),
                ('wallpaper', models.ImageField(blank=True, upload_to='')),
                ('rating', models.FloatField(default=0.0)),
                ('members_amount', models.IntegerField(default=0)),
                ('date_create', models.DateField(default=datetime.date.today)),
                ('path', models.CharField(blank=True, max_length=64)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
