# Generated by Django 4.0.4 on 2022-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_course_course_path_remove_profile_user_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
