# Generated by Django 4.0.4 on 2022-05-21 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='ProfileCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(blank=True)),
                ('date_added', models.DateField(default=datetime.date.today)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collection')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
            ],
        ),
    ]
