# Generated by Django 4.0.4 on 2022-05-21 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_coursestatus_name_profilecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecourse',
            name='point',
            field=models.IntegerField(blank=True, default=datetime.datetime(2022, 5, 21, 17, 3, 29, 854797, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='rating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
