# Generated by Django 4.0.4 on 2022-05-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_profilecourse_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecollection',
            name='point',
        ),
    ]
