# Generated by Django 4.0.4 on 2022-05-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_profilecollection_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecourse',
            name='point',
        ),
    ]
