# Generated by Django 4.0.4 on 2022-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_profilecourse_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecourse',
            name='point',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
