# Generated by Django 4.0.4 on 2022-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_profilecourse_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecollection',
            name='point',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
