# Generated by Django 4.0.4 on 2022-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_profilecollection_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecollection',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecourse',
            name='point',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
