# Generated by Django 4.0.4 on 2022-05-21 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_profilecollection_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_stars_count', models.IntegerField(default=0)),
                ('two_stars_count', models.IntegerField(default=0)),
                ('three_stars_count', models.IntegerField(default=0)),
                ('four_stars_count', models.IntegerField(default=0)),
                ('five_stars_count', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.collection')),
            ],
        ),
    ]
