# Generated by Django 4.0.4 on 2022-05-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
