# Generated by Django 4.0.4 on 2022-05-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_collection_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
