# Generated by Django 4.0.4 on 2022-05-23 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_collection_rating_alter_course_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecollection',
            name='date_added',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
