# Generated by Django 4.0.4 on 2022-05-24 18:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_profilecollection_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_url',
            field=models.ImageField(upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='path',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='path',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
