# Generated by Django 4.0.4 on 2022-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_collection_image_url_alter_course_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestep',
            name='mark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='step',
            name='max_mark',
            field=models.IntegerField(default=1),
        ),
    ]
