# Generated by Django 4.0.4 on 2022-05-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_profilestep_mark_step_max_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestars',
            name='course_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.courseinfo'),
        ),
    ]
