# Generated by Django 4.0.4 on 2022-05-25 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_coursestars_course_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionstars',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.collection'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
