# Generated by Django 4.0.4 on 2022-05-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_collectionstars_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecollection',
            old_name='point',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='profilecourse',
            old_name='point',
            new_name='grade',
        ),
    ]
