# Generated by Django 4.0.4 on 2022-05-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_rename_point_profilecollection_grade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='goal_description',
        ),
        migrations.RemoveField(
            model_name='courseinfo',
            name='title_image_url',
        ),
        migrations.RemoveField(
            model_name='coursestars',
            name='course_info',
        ),
        migrations.AddField(
            model_name='coursestars',
            name='course',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CourseMainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('goal_description', models.TextField()),
                ('course_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.courseinfo')),
            ],
        ),
    ]
