# Generated by Django 4.0.4 on 2022-05-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(default='profile-default.jpg', upload_to=''),
        ),
    ]
