# Generated by Django 4.0.4 on 2022-05-27 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileCourseRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='profilecourse',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profilecourserole'),
            preserve_default=False,
        ),
    ]
