# Generated by Django 4.0.4 on 2022-05-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_profilecourserole_profilecourse_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecourse',
            name='role',
        ),
    ]
