# Generated by Django 4.0.4 on 2022-05-27 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_profilecourse_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecourse',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.profilecourserole'),
        ),
    ]
