# Generated by Django 4.0.4 on 2022-05-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_profilecourse_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemaininfo',
            name='goal_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
