# Generated by Django 4.0.4 on 2022-05-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_profilecourse_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='goal',
            new_name='subscribing',
        ),
    ]
