# Generated by Django 4.0.4 on 2022-05-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_rename_goal_subscription_subscribing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribing', to='core.profile'),
        ),
    ]
