# Generated by Django 4.0.4 on 2022-05-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_subscription_subscribing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='subscribing',
        ),
        migrations.AddField(
            model_name='subscription',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='core.profile'),
            preserve_default=False,
        ),
    ]
