# Generated by Django 4.0.4 on 2022-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_remove_subscription_subscribing_subscription_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
    ]
