# Generated by Django 4.0.4 on 2022-05-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_creatorcollection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecourse',
            name='role',
        ),
    ]
