# Generated by Django 4.0.4 on 2022-05-31 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_profilecourse_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseCollection',
        ),
    ]
