# Generated by Django 4.0.4 on 2022-05-31 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_delete_coursecollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecourse',
            name='collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.collection'),
            preserve_default=False,
        ),
    ]
