# Generated by Django 4.0.4 on 2022-06-01 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_profilecourse_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecourse',
            name='status',
        ),
    ]
