# Generated by Django 4.0.4 on 2022-06-01 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_remove_profilecourse_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecourse',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profilecoursestatus'),
        ),
    ]
