# Generated by Django 4.0.4 on 2022-06-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_profilecourse_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecoursecollection',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collection'),
        ),
    ]
