# Generated by Django 4.0.4 on 2022-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_alter_profilecoursecollection_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='max_mark',
            new_name='max_progress',
        ),
        migrations.AddField(
            model_name='lesson',
            name='max_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='theme',
            name='max_progress',
            field=models.IntegerField(default=0),
        ),
    ]
