# Generated by Django 4.0.4 on 2022-06-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_rename_max_mark_step_max_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelesson',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profiletheme',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
