# Generated by Django 4.0.4 on 2022-06-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_profilelesson_progress_profiletheme_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='path',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='path',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
