# Generated by Django 4.0.4 on 2022-06-01 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_lesson_path_theme_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_url',
            field=models.ImageField(blank=True, default='default/collection-default.png', null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='course',
            name='avatar_url',
            field=models.ImageField(blank=True, default='default/course-default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image_url',
            field=models.ImageField(default='default/lesson-default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(default='default/profile-default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image_url',
            field=models.ImageField(default='default/theme-default.png', upload_to=''),
        ),
    ]
