# Generated by Django 4.0.4 on 2022-06-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_collection_image_url_alter_course_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image_url',
            field=models.ImageField(blank=True, default='default/lesson-default.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image_url',
            field=models.ImageField(blank=True, default='default/theme-default.png', null=True, upload_to=''),
        ),
    ]
