# Generated by Django 4.0.4 on 2022-06-01 23:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_lesson_image_url_alter_theme_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_url',
            field=models.ImageField(blank=True, default='default-collection.png', null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='course',
            name='avatar_url',
            field=models.ImageField(blank=True, default='default-course.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image_url',
            field=models.ImageField(blank=True, default='default-lesson.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.ImageField(default='default-profile.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image_url',
            field=models.ImageField(blank=True, default='default-theme.png', null=True, upload_to=''),
        ),
    ]
