# Generated by Django 4.0.4 on 2022-06-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_collection_image_url_alter_course_avatar_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='path',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='path',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
