# Generated by Django 4.0.4 on 2022-06-02 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_typestep_step_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='type',
        ),
        migrations.DeleteModel(
            name='TypeStep',
        ),
    ]
