# Generated by Django 4.0.4 on 2022-06-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_step_type_delete_typestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='path',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
