# Generated by Django 4.0.4 on 2022-06-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_step_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='avatar_url',
            new_name='image_url',
        ),
    ]
