# Generated by Django 4.0.4 on 2022-06-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_profileactionslogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
