# Generated by Django 4.0.4 on 2022-06-03 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_step_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='max_progress_points',
            new_name='max_progress',
        ),
    ]
