# Generated by Django 4.0.4 on 2022-06-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_rename_max_progress_points_course_max_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='max_progress',
            field=models.IntegerField(default=0),
        ),
    ]
