# Generated by Django 4.0.4 on 2022-06-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_alter_coursefit_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefit',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
