# Generated by Django 4.0.4 on 2022-06-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_alter_coursefit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='path',
            field=models.CharField(max_length=64),
        ),
    ]
