# Generated by Django 4.0.4 on 2022-06-05 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_profile_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilestep',
            old_name='mark',
            new_name='progress',
        ),
    ]
